# Generated by Django 4.1 on 2022-09-09 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_alter_todo_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_author',
        ),
        migrations.AddField(
            model_name='todo',
            name='user_author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
    ]
