# Generated by Django 4.1 on 2022-09-22 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_remove_todo_user_author_todo_user_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_author',
        ),
        migrations.AddField(
            model_name='todo',
            name='user_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
    ]
